### ISSUE TITLE
Request  for firmware version 1.7.6

### ISSUE THREAD

**Issue by jobitjoseph** [erdc/ACEstat_Firmware#1]
Dear team, really appreciate your work. If possible kindly provide the firmware version 1.7.6 . Thank you.

**Comment by ERDC-JasonRay** [comment]
Apologies on the delay for this.  I've been working on updating this to match our internal repository.  It should be updated now, let me know if it works.

**Comment by jobitjoseph** [comment]
@ERDC-JasonRay Thanks for the firmware update. Will check and let you know. Thank you.
